In [3]:
import cv2
import numpy as np

In [9]:
cap  = cv2.VideoCapture(0)
def nothing(x):
    pass
cv2.namedWindow("TrackBars")
cv2.createTrackbar("L-H","TrackBars",0,180,nothing)
cv2.createTrackbar("L-S","TrackBars",123,255,nothing)
cv2.createTrackbar("L-V","TrackBars",202,255,nothing)
cv2.createTrackbar("U-H","TrackBars",180,180,nothing)
cv2.createTrackbar("U-S","TrackBars",255,255,nothing)
cv2.createTrackbar("U-V","TrackBars",255,255,nothing)
font = cv2.FONT_HERSHEY_COMPLEX
while True:
    (_,img) = cap.read()
    hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    l_h = cv2.getTrackbarPos("L-H","TrackBars")
    l_s = cv2.getTrackbarPos("L-S","TrackBars")
    l_v = cv2.getTrackbarPos("L-V","TrackBars")
    u_h = cv2.getTrackbarPos("U-H","TrackBars")
    u_s = cv2.getTrackbarPos("U-S","TrackBars")
    u_v = cv2.getTrackbarPos("U-V","TrackBars")
    lower_red = np.array([l_h,l_s,l_v])
    upper_red = np.array([u_h,u_s,u_v])
#     mask = cv2.inRange(hsv,lower_red,upper_red)
#     kernel = np.ones((5,5),np.uint8)
#     mask = cv2.erode(mask,kernel)
#     contours,_ = cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#     for cnt in contours:
#         area = cv2.contourArea(cnt)
#         approx = cv2.approxPolyDP(cnt,0.01*cv2.arcLength(cnt,True),True)
#         if area>400:
#             cv2.drawContours(img,[approx],0,(0,0,0),5)
#             if len(approx) == 4:
#                 #print(approx)
#                 cv2.putText(img,"Rectangle",(approx[0][0][0],approx[0][0][1]),font,1,(0,0,0))
    cv2.imshow("img",img)
    cv2.imshow("mask",hsv)
    key = cv2.waitKey(10)
    if key == 27:
        break
cap.release()
cv2.destroyAllWindows()

NameError: name 'approx' is not defined

In [10]:
print(approx[0])
print(approx[1])
print(approx[2])
print(approx[3])

[[559  64]]
[[256 100]]
[[278 273]]
[[573 238]]


In [7]:
approx[0][0][0]

511